#!/usr/bin/env python3
import sys
import time

def main():
	print("Content-type: text/html\n")
	# sys.stdout.flush()

	print("<html>")
	print("<head>")
	print("<title>My CGI Document</title>")
	print("</head>")
	print("<body>")
	print("<h1>Hello, CGI World!</h1>")
	print("<p>This is a document generated by a Python script.</p>")
	print("</body>")
	print("</html>")
	return 0

if __name__ == "__main__":
    main()


# #!/usr/bin/env python3

# # This script is designed to fail and produce a 500 Internal Server Error.

# import sys

# # Step 1: Deliberately SKIP the required HTTP Header.
# # A correct script would have:
# # print("Content-type: text/html\n")
# # print() 

# # Step 2: Print data directly to standard output (stdout) instead.
# # The web server will see this text and won't know what to do with it, 
# # as it's missing the required 'Content-type' header.

# print("This text is being printed, but the server won't recognize it as a valid HTTP response.")
# print("The script is now exiting with an explicit error code.")

# # Step 3: Exit with a non-zero status code, which also signals a failure 
# # to many web servers. This reinforces the error state.
# sys.exit(1) 